### ISSUE TITLE
getByTitle returns single entity only

### ISSUE THREAD

**Issue by white-collar** [kostyanet/hibernate-task#4]
https://github.com/kostyanet/hibernate-task/blob/a4ff23ddd6cb324d461300e222cbdb48502b720a/src/main/java/dao/AutoDao.java#L103

Semantic of this method assumes that returned set of data may contains more than one single entity, isn't it ? If I enter "Tesla", for example, I can expect that there will be more than one vehicle.

**Comment by kostyanet** [comment]
@white-collar 
Please, see my MR
https://github.com/kostyanet/hibernate-task/pull/5
